//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Inputs/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""a8ceace3-f3c3-4f82-b73e-83b3ee2a398a"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""2270cbf0-9ad1-468a-a8e3-8856e9c16372"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a4f0e733-1751-472b-8763-77e985e67d32"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e44d5c2f-3410-48e0-8393-4e3082bb44fe"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4294eccb-9c70-402a-a712-04ac20412ede"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""471395a5-4d43-4b51-b770-8f52cbb00025"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ebe57808-bdaa-447b-8314-2972f4510339"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Drone"",
            ""id"": ""fe2dcbf3-c755-440b-b4b6-650b20a2a034"",
            ""actions"": [
                {
                    ""name"": ""HorizontalMovement"",
                    ""type"": ""Value"",
                    ""id"": ""c31b17a7-6e5a-4261-ae15-62b994fa4f15"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""VerticalMovement"",
                    ""type"": ""Value"",
                    ""id"": ""c2cfb294-5fb7-46a6-896f-ef1dea49ba46"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""14fc3eb1-f039-4fda-8afa-71b12f38426c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""c5988dba-5bb7-452f-b6eb-d8f30cdd13a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""2422cd92-0e58-453d-bf85-ceaec993a6f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f7ec8a9e-38b4-4888-ab51-0ed68112e89c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6b0a2037-87b9-496f-9838-1ef6ffd1e353"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""99ecefc7-e507-43d5-919c-6572de83d7b2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""787460de-fbce-481b-a51b-3019117274c9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fbb33d3f-eb3b-410b-9218-50b7b13da01e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HorizontalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""85e3b34f-5cde-4a20-8461-e70e9e41d1e7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""06c4dfc4-05a7-46dd-b2dd-3a17ac28bdc1"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""26309972-0097-4a8a-b782-06da4827646c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VerticalMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""c31537c3-c9b4-4458-a956-5b327de302cc"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""390f44f2-f7f0-4b40-8187-f6d916caf956"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""fa5e87c2-4c86-4365-933e-06f471868770"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0f919920-4764-4005-a496-1525822dfd16"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cffbe9f0-0be7-47af-b93d-0d31f45d9cbf"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Forklift"",
            ""id"": ""29ce0b67-a035-42a9-b213-8de5f8c59a8c"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""36bf5b8e-979d-45fc-92a6-fddc75529fd3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Lift"",
                    ""type"": ""Value"",
                    ""id"": ""d5e69631-7a8a-414c-8e2c-afeb8bde9658"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""8a1a53fa-fc3d-4d36-ade9-34746e7ccfdc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""3460f5e1-b4db-4eb8-9c71-026c4db2fc31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""00644458-f154-464d-9f3b-6a83e35e9129"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cb3b6cf9-519e-42ab-94af-69b414cc4de2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d6fd9124-42d2-41c9-ba83-548a18f7c562"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""962f5bb8-5240-40b8-9cbf-3bb3768a0816"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2b410002-e1c2-4551-92c3-66d0570b8fb2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""a025df83-0051-4421-9ea4-29ea0f28da67"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lift"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""492d9505-2059-42e3-b5e6-389033e381fe"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""4ea84954-4e25-4422-8d01-78786f9e9113"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3009e7b5-2824-49a1-b737-61f217f318d8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e40d1dcf-8360-4d1f-96f2-af55a009feae"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Detonator"",
            ""id"": ""5f7cbf7c-6493-4c59-ac57-bad3b15d9ca2"",
            ""actions"": [
                {
                    ""name"": ""PickupC4"",
                    ""type"": ""Button"",
                    ""id"": ""00a915a2-f0df-4aa7-84cd-69a9d0e91c04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaceC4"",
                    ""type"": ""Button"",
                    ""id"": ""4a69881f-0fb5-49ca-93bd-92adbb870ccd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DetonateC4"",
                    ""type"": ""Button"",
                    ""id"": ""6dadcead-22f7-4314-87d6-a3ec0eff9c30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""41cb81c4-fe20-4b51-9285-eee79d249af8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickupC4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4be61ac0-f529-4288-b6b2-39943b82ca1b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceC4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a533e2fd-8b0f-4907-9b0c-112a45109d7d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DetonateC4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Laptop"",
            ""id"": ""2e7e2803-950b-4a3f-ad07-4a9b99cbf2e4"",
            ""actions"": [
                {
                    ""name"": ""Hack"",
                    ""type"": ""Button"",
                    ""id"": ""e49a4b6f-37f6-4bef-a8fd-f1df07db70fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCameras"",
                    ""type"": ""Button"",
                    ""id"": ""d562571c-1d11-4922-9684-f7ee8768dbc5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""2afb941c-bbc8-4b86-abaa-8261872d171e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f6e32146-b498-40f6-9873-c4fde59112ef"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold(duration=5)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e2c8c0c-bff8-4c9a-a883-f04989b8ce1e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCameras"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e98e5be-4f8b-4646-a58a-9d471026638f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""EndZone"",
            ""id"": ""1a2a8422-c42d-4348-a4fe-f607cb0867d8"",
            ""actions"": [
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""a4094aa6-efe7-45e8-b1f8-941efa006234"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""11f65343-c98e-4699-9bbe-99df855f5ce3"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Crate"",
            ""id"": ""1f1b6714-e3d4-4c42-bd1f-7a6c66e67962"",
            ""actions"": [
                {
                    ""name"": ""Break"",
                    ""type"": ""Button"",
                    ""id"": ""68327cb4-4131-4f03-82fa-6b79a887d2ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DoubleBreak"",
                    ""type"": ""Button"",
                    ""id"": ""8d194c33-c31b-4611-867b-76612a448038"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a7bbe8df-b374-4c9e-889f-a799670215ad"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Break"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""340b2828-3ffd-458f-a58d-b89b9aecf2ce"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold(duration=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DoubleBreak"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        // Drone
        m_Drone = asset.FindActionMap("Drone", throwIfNotFound: true);
        m_Drone_HorizontalMovement = m_Drone.FindAction("HorizontalMovement", throwIfNotFound: true);
        m_Drone_VerticalMovement = m_Drone.FindAction("VerticalMovement", throwIfNotFound: true);
        m_Drone_Rotation = m_Drone.FindAction("Rotation", throwIfNotFound: true);
        m_Drone_Escape = m_Drone.FindAction("Escape", throwIfNotFound: true);
        m_Drone_Enter = m_Drone.FindAction("Enter", throwIfNotFound: true);
        // Forklift
        m_Forklift = asset.FindActionMap("Forklift", throwIfNotFound: true);
        m_Forklift_Movement = m_Forklift.FindAction("Movement", throwIfNotFound: true);
        m_Forklift_Lift = m_Forklift.FindAction("Lift", throwIfNotFound: true);
        m_Forklift_Escape = m_Forklift.FindAction("Escape", throwIfNotFound: true);
        m_Forklift_Enter = m_Forklift.FindAction("Enter", throwIfNotFound: true);
        // Detonator
        m_Detonator = asset.FindActionMap("Detonator", throwIfNotFound: true);
        m_Detonator_PickupC4 = m_Detonator.FindAction("PickupC4", throwIfNotFound: true);
        m_Detonator_PlaceC4 = m_Detonator.FindAction("PlaceC4", throwIfNotFound: true);
        m_Detonator_DetonateC4 = m_Detonator.FindAction("DetonateC4", throwIfNotFound: true);
        // Laptop
        m_Laptop = asset.FindActionMap("Laptop", throwIfNotFound: true);
        m_Laptop_Hack = m_Laptop.FindAction("Hack", throwIfNotFound: true);
        m_Laptop_SwitchCameras = m_Laptop.FindAction("SwitchCameras", throwIfNotFound: true);
        m_Laptop_Escape = m_Laptop.FindAction("Escape", throwIfNotFound: true);
        // EndZone
        m_EndZone = asset.FindActionMap("EndZone", throwIfNotFound: true);
        m_EndZone_Restart = m_EndZone.FindAction("Restart", throwIfNotFound: true);
        // Crate
        m_Crate = asset.FindActionMap("Crate", throwIfNotFound: true);
        m_Crate_Break = m_Crate.FindAction("Break", throwIfNotFound: true);
        m_Crate_DoubleBreak = m_Crate.FindAction("DoubleBreak", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Drone
    private readonly InputActionMap m_Drone;
    private IDroneActions m_DroneActionsCallbackInterface;
    private readonly InputAction m_Drone_HorizontalMovement;
    private readonly InputAction m_Drone_VerticalMovement;
    private readonly InputAction m_Drone_Rotation;
    private readonly InputAction m_Drone_Escape;
    private readonly InputAction m_Drone_Enter;
    public struct DroneActions
    {
        private @PlayerInputActions m_Wrapper;
        public DroneActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @HorizontalMovement => m_Wrapper.m_Drone_HorizontalMovement;
        public InputAction @VerticalMovement => m_Wrapper.m_Drone_VerticalMovement;
        public InputAction @Rotation => m_Wrapper.m_Drone_Rotation;
        public InputAction @Escape => m_Wrapper.m_Drone_Escape;
        public InputAction @Enter => m_Wrapper.m_Drone_Enter;
        public InputActionMap Get() { return m_Wrapper.m_Drone; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DroneActions set) { return set.Get(); }
        public void SetCallbacks(IDroneActions instance)
        {
            if (m_Wrapper.m_DroneActionsCallbackInterface != null)
            {
                @HorizontalMovement.started -= m_Wrapper.m_DroneActionsCallbackInterface.OnHorizontalMovement;
                @HorizontalMovement.performed -= m_Wrapper.m_DroneActionsCallbackInterface.OnHorizontalMovement;
                @HorizontalMovement.canceled -= m_Wrapper.m_DroneActionsCallbackInterface.OnHorizontalMovement;
                @VerticalMovement.started -= m_Wrapper.m_DroneActionsCallbackInterface.OnVerticalMovement;
                @VerticalMovement.performed -= m_Wrapper.m_DroneActionsCallbackInterface.OnVerticalMovement;
                @VerticalMovement.canceled -= m_Wrapper.m_DroneActionsCallbackInterface.OnVerticalMovement;
                @Rotation.started -= m_Wrapper.m_DroneActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_DroneActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_DroneActionsCallbackInterface.OnRotation;
                @Escape.started -= m_Wrapper.m_DroneActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_DroneActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_DroneActionsCallbackInterface.OnEscape;
                @Enter.started -= m_Wrapper.m_DroneActionsCallbackInterface.OnEnter;
                @Enter.performed -= m_Wrapper.m_DroneActionsCallbackInterface.OnEnter;
                @Enter.canceled -= m_Wrapper.m_DroneActionsCallbackInterface.OnEnter;
            }
            m_Wrapper.m_DroneActionsCallbackInterface = instance;
            if (instance != null)
            {
                @HorizontalMovement.started += instance.OnHorizontalMovement;
                @HorizontalMovement.performed += instance.OnHorizontalMovement;
                @HorizontalMovement.canceled += instance.OnHorizontalMovement;
                @VerticalMovement.started += instance.OnVerticalMovement;
                @VerticalMovement.performed += instance.OnVerticalMovement;
                @VerticalMovement.canceled += instance.OnVerticalMovement;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
            }
        }
    }
    public DroneActions @Drone => new DroneActions(this);

    // Forklift
    private readonly InputActionMap m_Forklift;
    private IForkliftActions m_ForkliftActionsCallbackInterface;
    private readonly InputAction m_Forklift_Movement;
    private readonly InputAction m_Forklift_Lift;
    private readonly InputAction m_Forklift_Escape;
    private readonly InputAction m_Forklift_Enter;
    public struct ForkliftActions
    {
        private @PlayerInputActions m_Wrapper;
        public ForkliftActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Forklift_Movement;
        public InputAction @Lift => m_Wrapper.m_Forklift_Lift;
        public InputAction @Escape => m_Wrapper.m_Forklift_Escape;
        public InputAction @Enter => m_Wrapper.m_Forklift_Enter;
        public InputActionMap Get() { return m_Wrapper.m_Forklift; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ForkliftActions set) { return set.Get(); }
        public void SetCallbacks(IForkliftActions instance)
        {
            if (m_Wrapper.m_ForkliftActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnMovement;
                @Lift.started -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnLift;
                @Lift.performed -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnLift;
                @Lift.canceled -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnLift;
                @Escape.started -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnEscape;
                @Enter.started -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnEnter;
                @Enter.performed -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnEnter;
                @Enter.canceled -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnEnter;
            }
            m_Wrapper.m_ForkliftActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Lift.started += instance.OnLift;
                @Lift.performed += instance.OnLift;
                @Lift.canceled += instance.OnLift;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
            }
        }
    }
    public ForkliftActions @Forklift => new ForkliftActions(this);

    // Detonator
    private readonly InputActionMap m_Detonator;
    private IDetonatorActions m_DetonatorActionsCallbackInterface;
    private readonly InputAction m_Detonator_PickupC4;
    private readonly InputAction m_Detonator_PlaceC4;
    private readonly InputAction m_Detonator_DetonateC4;
    public struct DetonatorActions
    {
        private @PlayerInputActions m_Wrapper;
        public DetonatorActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PickupC4 => m_Wrapper.m_Detonator_PickupC4;
        public InputAction @PlaceC4 => m_Wrapper.m_Detonator_PlaceC4;
        public InputAction @DetonateC4 => m_Wrapper.m_Detonator_DetonateC4;
        public InputActionMap Get() { return m_Wrapper.m_Detonator; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DetonatorActions set) { return set.Get(); }
        public void SetCallbacks(IDetonatorActions instance)
        {
            if (m_Wrapper.m_DetonatorActionsCallbackInterface != null)
            {
                @PickupC4.started -= m_Wrapper.m_DetonatorActionsCallbackInterface.OnPickupC4;
                @PickupC4.performed -= m_Wrapper.m_DetonatorActionsCallbackInterface.OnPickupC4;
                @PickupC4.canceled -= m_Wrapper.m_DetonatorActionsCallbackInterface.OnPickupC4;
                @PlaceC4.started -= m_Wrapper.m_DetonatorActionsCallbackInterface.OnPlaceC4;
                @PlaceC4.performed -= m_Wrapper.m_DetonatorActionsCallbackInterface.OnPlaceC4;
                @PlaceC4.canceled -= m_Wrapper.m_DetonatorActionsCallbackInterface.OnPlaceC4;
                @DetonateC4.started -= m_Wrapper.m_DetonatorActionsCallbackInterface.OnDetonateC4;
                @DetonateC4.performed -= m_Wrapper.m_DetonatorActionsCallbackInterface.OnDetonateC4;
                @DetonateC4.canceled -= m_Wrapper.m_DetonatorActionsCallbackInterface.OnDetonateC4;
            }
            m_Wrapper.m_DetonatorActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PickupC4.started += instance.OnPickupC4;
                @PickupC4.performed += instance.OnPickupC4;
                @PickupC4.canceled += instance.OnPickupC4;
                @PlaceC4.started += instance.OnPlaceC4;
                @PlaceC4.performed += instance.OnPlaceC4;
                @PlaceC4.canceled += instance.OnPlaceC4;
                @DetonateC4.started += instance.OnDetonateC4;
                @DetonateC4.performed += instance.OnDetonateC4;
                @DetonateC4.canceled += instance.OnDetonateC4;
            }
        }
    }
    public DetonatorActions @Detonator => new DetonatorActions(this);

    // Laptop
    private readonly InputActionMap m_Laptop;
    private ILaptopActions m_LaptopActionsCallbackInterface;
    private readonly InputAction m_Laptop_Hack;
    private readonly InputAction m_Laptop_SwitchCameras;
    private readonly InputAction m_Laptop_Escape;
    public struct LaptopActions
    {
        private @PlayerInputActions m_Wrapper;
        public LaptopActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Hack => m_Wrapper.m_Laptop_Hack;
        public InputAction @SwitchCameras => m_Wrapper.m_Laptop_SwitchCameras;
        public InputAction @Escape => m_Wrapper.m_Laptop_Escape;
        public InputActionMap Get() { return m_Wrapper.m_Laptop; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LaptopActions set) { return set.Get(); }
        public void SetCallbacks(ILaptopActions instance)
        {
            if (m_Wrapper.m_LaptopActionsCallbackInterface != null)
            {
                @Hack.started -= m_Wrapper.m_LaptopActionsCallbackInterface.OnHack;
                @Hack.performed -= m_Wrapper.m_LaptopActionsCallbackInterface.OnHack;
                @Hack.canceled -= m_Wrapper.m_LaptopActionsCallbackInterface.OnHack;
                @SwitchCameras.started -= m_Wrapper.m_LaptopActionsCallbackInterface.OnSwitchCameras;
                @SwitchCameras.performed -= m_Wrapper.m_LaptopActionsCallbackInterface.OnSwitchCameras;
                @SwitchCameras.canceled -= m_Wrapper.m_LaptopActionsCallbackInterface.OnSwitchCameras;
                @Escape.started -= m_Wrapper.m_LaptopActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_LaptopActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_LaptopActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_LaptopActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Hack.started += instance.OnHack;
                @Hack.performed += instance.OnHack;
                @Hack.canceled += instance.OnHack;
                @SwitchCameras.started += instance.OnSwitchCameras;
                @SwitchCameras.performed += instance.OnSwitchCameras;
                @SwitchCameras.canceled += instance.OnSwitchCameras;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public LaptopActions @Laptop => new LaptopActions(this);

    // EndZone
    private readonly InputActionMap m_EndZone;
    private IEndZoneActions m_EndZoneActionsCallbackInterface;
    private readonly InputAction m_EndZone_Restart;
    public struct EndZoneActions
    {
        private @PlayerInputActions m_Wrapper;
        public EndZoneActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Restart => m_Wrapper.m_EndZone_Restart;
        public InputActionMap Get() { return m_Wrapper.m_EndZone; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EndZoneActions set) { return set.Get(); }
        public void SetCallbacks(IEndZoneActions instance)
        {
            if (m_Wrapper.m_EndZoneActionsCallbackInterface != null)
            {
                @Restart.started -= m_Wrapper.m_EndZoneActionsCallbackInterface.OnRestart;
                @Restart.performed -= m_Wrapper.m_EndZoneActionsCallbackInterface.OnRestart;
                @Restart.canceled -= m_Wrapper.m_EndZoneActionsCallbackInterface.OnRestart;
            }
            m_Wrapper.m_EndZoneActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Restart.started += instance.OnRestart;
                @Restart.performed += instance.OnRestart;
                @Restart.canceled += instance.OnRestart;
            }
        }
    }
    public EndZoneActions @EndZone => new EndZoneActions(this);

    // Crate
    private readonly InputActionMap m_Crate;
    private ICrateActions m_CrateActionsCallbackInterface;
    private readonly InputAction m_Crate_Break;
    private readonly InputAction m_Crate_DoubleBreak;
    public struct CrateActions
    {
        private @PlayerInputActions m_Wrapper;
        public CrateActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Break => m_Wrapper.m_Crate_Break;
        public InputAction @DoubleBreak => m_Wrapper.m_Crate_DoubleBreak;
        public InputActionMap Get() { return m_Wrapper.m_Crate; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CrateActions set) { return set.Get(); }
        public void SetCallbacks(ICrateActions instance)
        {
            if (m_Wrapper.m_CrateActionsCallbackInterface != null)
            {
                @Break.started -= m_Wrapper.m_CrateActionsCallbackInterface.OnBreak;
                @Break.performed -= m_Wrapper.m_CrateActionsCallbackInterface.OnBreak;
                @Break.canceled -= m_Wrapper.m_CrateActionsCallbackInterface.OnBreak;
                @DoubleBreak.started -= m_Wrapper.m_CrateActionsCallbackInterface.OnDoubleBreak;
                @DoubleBreak.performed -= m_Wrapper.m_CrateActionsCallbackInterface.OnDoubleBreak;
                @DoubleBreak.canceled -= m_Wrapper.m_CrateActionsCallbackInterface.OnDoubleBreak;
            }
            m_Wrapper.m_CrateActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Break.started += instance.OnBreak;
                @Break.performed += instance.OnBreak;
                @Break.canceled += instance.OnBreak;
                @DoubleBreak.started += instance.OnDoubleBreak;
                @DoubleBreak.performed += instance.OnDoubleBreak;
                @DoubleBreak.canceled += instance.OnDoubleBreak;
            }
        }
    }
    public CrateActions @Crate => new CrateActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
    }
    public interface IDroneActions
    {
        void OnHorizontalMovement(InputAction.CallbackContext context);
        void OnVerticalMovement(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
    }
    public interface IForkliftActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnLift(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
    }
    public interface IDetonatorActions
    {
        void OnPickupC4(InputAction.CallbackContext context);
        void OnPlaceC4(InputAction.CallbackContext context);
        void OnDetonateC4(InputAction.CallbackContext context);
    }
    public interface ILaptopActions
    {
        void OnHack(InputAction.CallbackContext context);
        void OnSwitchCameras(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IEndZoneActions
    {
        void OnRestart(InputAction.CallbackContext context);
    }
    public interface ICrateActions
    {
        void OnBreak(InputAction.CallbackContext context);
        void OnDoubleBreak(InputAction.CallbackContext context);
    }
}
